create table GS_APP_DATA (ID bigint generated by default as identity, APP_URL varchar(255), USER_ID bigint, primary key (ID));

create table GS_GADGET (GAGET_ID bigint generated by default as identity, GADGET_AUTHOR varchar(255), GADGET_AUTHOR_EMAIL varchar(255), GADGET_DESCRIPTION varchar(255), GADGET_GROUP binary(255), GADGET_SCREENSHOT_URL varchar(255), GADGET_THUMBNAIL_URL varchar(255), GADGET_TITLE varchar(255), GADGET_TITLE_URL varchar(255), GADGET_TYPE varchar(255), GADGET_URL varchar(255), primary key (GAGET_ID));

create table GS_GROUP (GROUP_ID bigint generated by default as identity, GROUP_DESC varchar(255), GROUP_NAME varchar(255), primary key (GROUP_ID));

create table GS_PAGE (PAGE_ID bigint generated by default as identity, PAGE_COLUMNS bigint, PAGE_NAME varchar(255), PAGE_ORDER bigint, PAGE_USER bigint, primary key (PAGE_ID));

create table GS_USER (ID bigint generated by default as identity, CURR_PAGE_ID bigint, DISPLAY_NAME varchar(255), EMAIL varchar(255), NAME varchar(255), USER_ROLE varchar(255), primary key (ID));

create table GS_USER_GROUP (USER_ID bigint not null, GROUP_ID bigint not null);

create table GS_WIDGET (WIDGET_ID bigint generated by default as identity, WIDGET_URL varchar(255), WIDGET_NAME varchar(255), WIDGET_ORDER bigint, page_PAGE_ID bigint, primary key (WIDGET_ID));

create table GS_WIDGET_PREF (WIDGET_PREF_ID bigint generated by default as identity, WIDGET_PREF_NAME varchar(255), WIDGET_PREF_VALUE varchar(255), widget_WIDGET_ID bigint, primary key (WIDGET_PREF_ID));

alter table GS_PAGE add constraint FK3EDCBE0268691C08 foreign key (PAGE_USER) references GS_USER;

alter table GS_USER_GROUP add constraint FKABFBC21E68691C08 foreign key (USER_ID) references GS_USER;

alter table GS_USER_GROUP add constraint FKABFBC21ED20070EC foreign key (GROUP_ID) references GS_GROUP;

alter table GS_WIDGET add constraint FK706A0F75EC27FD8 foreign key (page_PAGE_ID) references GS_PAGE;

alter table GS_WIDGET_PREF add constraint FK1EFAB46BD6F8D9AD foreign key (widget_WIDGET_ID) references GS_WIDGET;

